---
- name: Ensure nginx is installed
  ansible.builtin.package:
    name: nginx
    state: present

- name: Deploy nginx upstream/conf that proxies to backend:19999
  ansible.builtin.template:
    src: nginx_upstream.conf.j2
    dest: /etc/nginx/conf.d/backend_upstream.conf
    mode: '0644'
  notify: Reload nginx

- name: Ensure nginx is enabled and started
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
