---
- name: Install prerequisites
  become: yes
  block:
    - name: Install software-properties-common on Ubuntu
      apt:
        name: software-properties-common
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: Install prerequisites on Amazon Linux
      yum:
        name: curl
        state: present
      when: ansible_os_family == "RedHat"


- name: Install Netdata
  become: yes
  block:
    - name: Install Netdata on Ubuntu
      shell: curl -SsL https://my-netdata.io/kickstart.sh | bash
      args:
        executable: /bin/bash
      when: ansible_os_family == "Debian"


    - name: Install Netdata on Amazon Linux
      shell: curl -SsL https://my-netdata.io/kickstart.sh | bash
      args:
        executable: /bin/bash
      when: ansible_os_family == "RedHat"
